# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-04 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_auto_20160503_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='software',
            new_name='extra_info',
        ),
        migrations.AddField(
            model_name='note',
            name='reply_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorials.Note'),
        ),
        migrations.AddField(
            model_name='note',
            name='user_submitted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='author',
            field=models.CharField(default='Patrick', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorial',
            name='baseline',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='show_to_all',
            field=models.BooleanField(default=True),
        ),
    ]
