# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-24 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_auto_20160504_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorials.Note'),
        ),
    ]
