# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-24 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_auto_20160524_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='step_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='tutorials.Step'),
        ),
    ]
