# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-12 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0008_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='step_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
