# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-26 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0012_auto_20170526_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='num_ratings',
        ),
    ]
