# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-30 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0013_remove_note_num_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='stepList',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='note',
            name='type',
            field=models.CharField(blank=True, default='step', max_length=50),
        ),
    ]
