# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-30 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0014_auto_20170530_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='type',
        ),
    ]
