# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-30 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0016_auto_20170530_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='contributor',
            new_name='author',
        ),
    ]
