# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-30 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0017_auto_20170530_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='step_id',
        ),
        migrations.AddField(
            model_name='note',
            name='step_id',
            field=models.ManyToManyField(blank=True, null=True, related_name='notes', to='tutorials.Step'),
        ),
    ]
