# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-31 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0018_auto_20170530_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='dateSubmitted',
            field=models.CharField(blank=True, default='***', max_length=50),
        ),
    ]
