# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-30 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0019_note_datesubmitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='stepList',
        ),
    ]
