# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-03 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0020_remove_note_steplist'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='note_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='tutorials.Note'),
        ),
    ]
