# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-03 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0021_contributor_note_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='step_id',
            field=models.ManyToManyField(blank=True, related_name='notes', to='tutorials.Step'),
        ),
    ]
