# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-03 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0022_auto_20170703_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='note_id',
        ),
        migrations.AddField(
            model_name='contributor',
            name='note_id',
            field=models.ManyToManyField(blank=True, related_name='contributors', to='tutorials.Note'),
        ),
    ]
