# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-03 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0023_auto_20170703_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='note_id',
        ),
        migrations.AddField(
            model_name='note',
            name='contributor_list',
            field=models.ManyToManyField(blank=True, related_name='contributors', to='tutorials.Contributor'),
        ),
    ]
