# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-03 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0024_auto_20170703_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='rating',
        ),
        migrations.AlterField(
            model_name='note',
            name='contributor_list',
            field=models.ManyToManyField(blank=True, default=None, related_name='contributors', to='tutorials.Contributor'),
        ),
    ]
