# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-12 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0028_auto_20170712_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='baseline',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='show_to_all',
        ),
    ]
