# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-07-12 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0029_auto_20170712_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='contributor',
            name='current_interface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interface_access', to='tutorials.Interface'),
        ),
        migrations.AddField(
            model_name='contributor',
            name='interface_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interfaceOne', to='tutorials.Interface'),
        ),
        migrations.AddField(
            model_name='contributor',
            name='interface_three',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interfaceThree', to='tutorials.Interface'),
        ),
        migrations.AddField(
            model_name='contributor',
            name='interface_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interfaceTwo', to='tutorials.Interface'),
        ),
    ]
