# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-04 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0030_auto_20170712_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='tutorial_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorialOne', to='tutorials.Tutorial'),
        ),
    ]
