# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-10 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0031_auto_20170804_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='current_tutorial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='has_access', to='tutorials.Tutorial'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='tutorial_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutorialOne', to='tutorials.Tutorial'),
        ),
    ]
