# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-14 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0033_remove_contributor_current_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='current_tutorial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='has_access', to='tutorials.Tutorial'),
        ),
    ]
