# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-15 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0038_auto_20170815_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='content',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='contributor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='contributor_list',
            field=models.ManyToManyField(blank=True, default=None, related_name='contributors', to='tutorials.Contributor'),
        ),
        migrations.AddField(
            model_name='note',
            name='dateSubmitted',
            field=models.CharField(blank=True, default='***', max_length=50),
        ),
        migrations.AddField(
            model_name='note',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='extra_info',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='tutorials.Note'),
        ),
        migrations.AddField(
            model_name='note',
            name='tutorial_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='tutorials.Tutorial'),
        ),
        migrations.AddField(
            model_name='note',
            name='user_submitted',
            field=models.BooleanField(default=True),
        ),
    ]
