# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-15 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0039_auto_20170815_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='current_interface',
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='interface_one',
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='interface_three',
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='interface_two',
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='tutorial_one',
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='tutorial_three',
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='tutorial_two',
        ),
    ]
