# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-15 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0040_auto_20170815_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='current_interface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interface_access', to='tutorials.Interface'),
        ),
        migrations.AddField(
            model_name='contributor',
            name='interface_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interfaceOne', to='tutorials.Interface'),
        ),
        migrations.AddField(
            model_name='contributor',
            name='interface_three',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interfaceThree', to='tutorials.Interface'),
        ),
        migrations.AddField(
            model_name='contributor',
            name='interface_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interfaceTwo', to='tutorials.Interface'),
        ),
        migrations.AddField(
            model_name='contributor',
            name='tutorial_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutorialOne', to='tutorials.Tutorial'),
        ),
        migrations.AddField(
            model_name='contributor',
            name='tutorial_three',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutorialThree', to='tutorials.Tutorial'),
        ),
        migrations.AddField(
            model_name='contributor',
            name='tutorial_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutorialTwo', to='tutorials.Tutorial'),
        ),
    ]
