# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.CharField(default='***', max_length=255)),
            ],
        ),
    ]
